### ISSUE TITLE
Data documentation template and procedure

### ISSUE THREAD

**Issue by pmcwhannel** [DeltaE/delta-e-utils#10]
The data documentation procedure will be used to indicate how the documentation of new datasets should be executed. This procedure should indicate what information regarding the dataset should be documented and how it will be documented. This issue will need at least the following items:

_Item 1_: Template/schema for documentation of a dataset.
The purpose of the template is to ensure all datasets are consistently documented and make it easer for Delta-E+ members to search for datasets which will be beneficial to them. The template for a given dataset should be like a homepage for that dataset. It should provide all the necessary information to understand what the dataset captures, the units of the data, the technical details (resolution, spatial coverage, etc...). Not within the scope of this issue or task but something the template should include is some sort of tagging/indexing mechanism so datasets can be discoverable by categorical tags. Please see [Data Documentation Outcome Ideas](https://1sfu-my.sharepoint.com/:w:/r/personal/tniet_sfu_ca/_layouts/15/Doc.aspx?sourcedoc=%7B941637AA-DFB1-4379-85CC-6A159C5B10C6%7D&file=2022-10-11%20Data%20Documetation%20Outcomes.docx&action=default&mobileredirect=true) for some ideas on what the template should contain.

_Item 2_: Procedure for using the template
The procedure should outline the process of where to find the template, explain the purpose of the template and documentation of datasets, and all the steps involved in the process of creating the documentation for a new dataset.

A successful PR for this will include: 
- [x] Template/schema for documentation of a dataset.
- [x] Procedure for using the template.
- [x] A dedicated page where an example/tutorial is provided of following the procedure. (Possibly combined with procedure)

**Comment by trevorb1** [comment]
Just in relation to _Item 1_ is the [json-schema](https://json-schema.org/) site. Using this to validate all meta-data, either in script or through GitHub Actions, would be good. Even if the meta-data is stored in a yaml file, it will still work fine (see [here](https://stackoverflow.com/a/22231372/14961492))

**Comment by pmcwhannel** [comment]
Harnoor and Mo, completed this.

**Comment by trevorb1** [comment]
Done with PR #28
