### ISSUE TITLE
Gather Information on Current Datasets 

### ISSUE THREAD

**Issue by trevorb1** [DeltaE/delta-e-utils#12]
**Go to each project lead and collect the following information (Not exhaustive list)**: 
- [x] Collection process for data (PDFs, CSVs, Excel, Random sources from websites)
- [x] Regions covered by data
- [x] Time horizon covered
- [x] Temporal resoultion covered 
- [x] Category of data (power system, agriculture, water, ect...) 
- [x] Subtype of data (capacity factor, costs, ect...) 
- [x] Data format (Geospatial, csv, ect...)
- [x] Licence of data (speaks to governance and providence) 
- [x] Data publisher 
- [x] **Any other relevant data** 

**List of projects**:
- [ ] OSeMOSYS Global (Trevor)
- [ ] CLEWs Canada (Kamaria)
- [ ] BC Nexus (Nastaran/Elias)
- [ ] Energy Storage Modelling (Sina) 
- [ ] Laos Cascading Hydro (Yalda)
- [ ] Fleet Electrification (Kamaria)
- [ ] LCA (Teddy)
- [ ] BC PyPSA (Pierre)
- [ ] Vancouver Island PyPSA (Trevor)
- [ ] CLEWs Kenya (Yalda)
- [ ] Canada-USA (Sina/Trevor)
- [ ] CLEWs Global (Kamaria)
- [ ] Atlantic Canada (Narges)

**Considerations when reviewing data**: 
- Think about how to categorize data (by type, by producer of data, ect...) 
- How far down should `delta-e-utils` work? At what point do individual projects modify the data? This should be added eventually to the data addition tutorial/requirements.
- Review meeting [notes](https://1sfu-my.sharepoint.com/:f:/g/personal/tniet_sfu_ca/EqGglp7FwnNChsW229jrhO8BMoowyCgLrKcg3cJlty5oAg?e=n2MPf9) (This should be a good source of ideas which the team has already discussed prior to the work study students joining)

**What our preliminary big picture objectives are**: 
- Data documentation templates
- Searchable environment for datasets (likely ReadTheDocs)
- Organization for how datasets are stored (some sort of tagging system) 
- Auto links to code that is associated with the data 
- Avoid data and script redundancy 

**Steps to Complete**
1. Decide on preliminary template for how to collect data
2. Each student takes half the projects and collects data 
3. Students merge lists together and pull out potentially useful information (redundant data, ect...) 
4. Present final document to data team 

**Successful PR**:
- [ ] A master document summarizing the data currently used

**Comment by pmcwhannel** [comment]
Completed.
